# Generated by Django 5.2.17 on 2026-09-03 23:00

import django.db.models.deletion
import medicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Especialidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("matricula", models.CharField(max_length=10, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("fecha_de_ingreso", models.DateField(auto_now_add=True)),
                (
                    "code",
                    models.CharField(
                        default=medicos.models.generar_code, max_length=32, unique=True
                    ),
                ),
                (
                    "especialidad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medicos",
                        to="medicos.especialidades",
                    ),
                ),
            ],
        ),
    ]
