# Generated by Django 5.2.17 on 2026-08-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepartamentosMedicos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("nro_departamento", models.IntegerField(unique=True)),
                ("cantidad_medicos", models.IntegerField()),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("email", models.EmailField(max_length=100)),
            ],
        ),
    ]
